spring:
  application:
    name: pricey
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PriceyDB
    username: pricey
    password: 12345
  servlet:
    multipart:
      enabled: true
  sql:
    init:
      mode: always
  